# Generated by Django 4.0.5 on 2022-08-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_refeicao', models.CharField(max_length=40)),
                ('alimento', models.CharField(max_length=100)),
                ('qt_calorias', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Escolhendo_Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_refeicao', models.CharField(choices=[('C', 'Café da manhã'), ('A', 'Almoço'), ('J', 'Janta')], max_length=1)),
            ],
        ),
    ]
