# Generated by Django 4.0.5 on 2022-08-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contar_caloria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_refeicao', models.CharField(max_length=1)),
                ('nome_refeicao', models.TextField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente_Escolhendo_Refeicao',
        ),
    ]
